#!/bin/bash
set -e

RESOURCE_GROUP_NAME="koudaiii.com-terraform"
STORAGE_ACCOUNT_NAME="koudaiiicom"
CONTAINER_NAME=tfstate
SUBSCRIPTION_ID="fc2da8a8-dc82-4a28-8805-e7287bb7d20d"

# Login to Azure
az login

# Set the default subscription
az account set --subscription $SUBSCRIPTION_ID

# Create resource group
az group create --name $RESOURCE_GROUP_NAME --location eastus

# Create storage account
az storage account create --resource-group $RESOURCE_GROUP_NAME --name $STORAGE_ACCOUNT_NAME --sku Standard_LRS --encryption-services blob

# Create blob container
az storage container create --name $CONTAINER_NAME --account-name $STORAGE_ACCOUNT_NAME
